# Generated by Django 4.2.1 on 2023-06-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='imagenTecnologia',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/gonza/Desktop/Proyecto-coder/Proyecto/AppCoder/static/AppCoder/img'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='tecnologia',
            field=models.CharField(choices=[('celular', 'Celular'), ('computadora', 'Computadora'), ('consola', 'Consola'), ('otro', 'Otro')], default='tecnologia', max_length=15),
        ),
    ]
