# Generated by Django 4.2.2 on 2023-06-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(choices=[('celular', 'Celular'), ('computadora', 'Computadora'), ('consola', 'Consola')], default='celular', max_length=15),
        ),
    ]
