# Generated by Django 4.2.2 on 2023-06-30 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0013_alter_producto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='comprador',
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
