# Generated by Django 4.2.2 on 2023-06-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
    ]
