# Generated by Django 4.2.2 on 2023-07-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0021_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
    ]
