# Generated by Django 4.2.2 on 2023-07-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0027_alter_producto_imagenproducto_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
